### ISSUE TITLE
문제 클릭시 목록으로 클릭시 데이터를 뿌리지 않음

### ISSUE THREAD

**Issue by kzsc5464** [sdf5771/qualk#4]
test가 아닌 위키 문제 중에서 문제를 클릭하고 목록으로 클릭시에 API로 데이터를 불러오지 않음

**Comment by sdf5771** [comment]
해당 이슈는 기존 URL 구조가 변경되면서 생긴 오류 입니다.

기존 URL : https://qualk.co.kr/quiz
변경 된 URL : http://localhost:3000/quiz/gaiq

react router dom에 useNavigate 함수 사용 시 인자 값을 기존 URL 값으로 변경시켜주어 생기는 버그이며,
해당 이슈는 모의고사 기능이 본 서버에 업데이트 되는 당시 같이 수정되어 배포될 예정입니다.

감사합니다.

**Comment by sdf5771** [comment]
issue close
